{% extends 'base.html.twig' %}

{% block title %}Hello MainController!{% endblock %}
{#comentario de mi código#}
{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    <h2> {{ created_by }} </h2>


    <table class="table">
        <thead>
        <tr>
            <th>Name</th>
            <th>Lastname</th>
            <th>Department</th>
            <th>Nwatch</th>
        </tr>
        </thead>
        <tbody>
        {% for twatch in twatches %}
        <tr>
            <td>{{ twatch.teacher.name }}</td>
            <td>{{ twatch.teacher.lastname }}</td>
            <td>{{ twatch.teacher.department }}</td>
            <td>{{ twatch.teacher.nwatch }}</td>
        </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/home/jc/symfony_projects/daw_fct/src/Controller/MainController.php'|file_link(0) }}">src/Controller/MainController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/home/jc/symfony_projects/daw_fct/templates/main/index.html.twig'|file_link(0) }}">templates/main/index.html.twig</a></code></li>
    </ul>
</div>
    {% block footer %} {% endblock %}
{% endblock %}
